USE [SPRINGMVC]
GO

/****** Object:  Table [dbo].[FRESHER]    Script Date: 3/15/2017 10:22:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FRESHER](
	[FRESHER_ID] [int] IDENTITY(1,1) NOT NULL,
	[FULLNAME] [nvarchar](500) NULL,
	[EMAIl] [nvarchar](500) NULL,
	[PROFESSION] [nvarchar](500) NULL,
 CONSTRAINT [PK_FRESHER] PRIMARY KEY CLUSTERED 
(
	[FRESHER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

